version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GIN_MODE=release
    restart: unless-stopped


  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - API_URL=http://localhost:8080/api/v1
    ports:
      - "5175:5175"
    environment:
      - NODE_ENV=development
    depends_on:
      - server

networks:
  app-network:
    driver: bridge